# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWinGui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(784, 595)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.actBtn = QtWidgets.QPushButton(self.widget)
        self.actBtn.setObjectName("actBtn")
        self.gridLayout_3.addWidget(self.actBtn, 1, 1, 1, 1)
        self.actEdit = QtWidgets.QLineEdit(self.widget)
        self.actEdit.setObjectName("actEdit")
        self.gridLayout_3.addWidget(self.actEdit, 1, 2, 1, 1)
        self.genEdit = QtWidgets.QLineEdit(self.widget)
        self.genEdit.setObjectName("genEdit")
        self.gridLayout_3.addWidget(self.genEdit, 0, 2, 1, 1)
        self.genBtn = QtWidgets.QPushButton(self.widget)
        self.genBtn.setObjectName("genBtn")
        self.gridLayout_3.addWidget(self.genBtn, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.startBtn = QtWidgets.QPushButton(self.widget_2)
        self.startBtn.setObjectName("startBtn")
        self.gridLayout_2.addWidget(self.startBtn, 0, 0, 1, 1)
        self.infoEdit = QtWidgets.QLineEdit(self.widget_2)
        self.infoEdit.setObjectName("infoEdit")
        self.gridLayout_2.addWidget(self.infoEdit, 1, 0, 1, 2)
        self.closeBtn = QtWidgets.QPushButton(self.widget_2)
        self.closeBtn.setObjectName("closeBtn")
        self.gridLayout_2.addWidget(self.closeBtn, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.closeBtn.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.actBtn.setText(_translate("MainWindow", "Activate"))
        self.genBtn.setText(_translate("MainWindow", "Generate UUID"))
        self.startBtn.setText(_translate("MainWindow", "Start"))
        self.closeBtn.setText(_translate("MainWindow", "Close"))
